### ISSUE TITLE
Change of Hasher

### ISSUE THREAD

**Issue by PlaneB** [jonhoo/rust-evmap#12]
Is it possible to change the hasher for key generation? For example in my case it makes sense to use https://crates.rs/crates/nohash-hasher as keys are already hash values.

**Comment by novacrazy** [comment]
You can use [`Options`](https://docs.rs/evmap/4.1.1/evmap/struct.Options.html) like so:

```rust
extern crate evmap;
extern crate nohash_hasher;

use nohash_hasher::BuildNoHashHasher;

/// whatever your key type is
type K = i32;

/// whatever your value type is
type V = i32;

fn main() {
    let (r, mut w) = evmap::Options::default()
        .with_hasher(BuildNoHashHasher::<K>::default())
        .construct::<K, V>();

    // ...
}
```

or use [`evmap::with_hasher`](https://docs.rs/evmap/4.1.1/evmap/fn.with_hasher.html)

**Comment by PlaneB** [comment]
Thanks. Nice crate by the way
