### ISSUE TITLE
Support multiple hashtable backends

### ISSUE THREAD

**Issue by novacrazy** [jonhoo/rust-evmap#14]
Branching off of https://github.com/Amanieu/hashbrown/issues/43

I'm not sure what the best way to do this is, so this issue is inviting ideas.

A simple start would be a trait such as:

```rust
pub trait Backend<K, V>: Extend<(K, V)>
where 
    K: Hash + Eq,
    V: Eq + ShallowCopy,
{
    fn apply_first(&mut self, ops: ...);
    fn apply_second(&mut self, ops: ...);

    unsafe fn clear_nodrop(&mut self);
}

impl<K, V, S> Backend<K, V> for hashbrown::HashMap<K, V, S>
where
    K: Hash + Eq,
    V: Eq + ShallowCopy,
    S: BuildHasher,
{ /*...*/ }

// also for std::collections::HashMap
// also for rahashmap::HashMap
// etc.
```

Perhaps the `S` hash builder parameter could be replaced with the above, so that:

```rust
pub struct WriteHandle<K, V, M = (), S = RandomState>
where
    K: Eq + Hash + Clone,
    S: BuildHasher + Clone,
    V: Eq + ShallowCopy,
    M: 'static + Clone,
{ /*...*/ }
```

becomes:

```rust
pub struct WriteHandle<K, V, M = (), B = hashbrown::HashMap<K, V, RandomState>>
where
    K: Eq + Hash + Clone,
    V: Eq + ShallowCopy,
    M: 'static + Clone,
    B: Backend<K, V>
{ /*...*/ }
```

This would allow us to leverage the particular features and algorithms for different libraries.

If necessary, two traits could be used to hide the real implementation:

```rust
mod internal {
    pub trait RealTrait {
        fn real_operation_we_dont_want_seen();
    }
}

pub trait PublicTrait: internal::RealTrait {}

impl<T> PublicTrait for T where T: internal::RealTrait {}

pub struct Structure<B>
where
    B: PublicTrait
{ /*...*/ }
```

**Comment by novacrazy** [comment]
Although, with the new design of operations in #13, where the application implementation is tied to the operations themselves rather than the writer, this may be a bit less straightforward. It should still be possible, though.

**Comment by jonhoo** [comment]
I think we should close this — though it would be nice to have a swappable backend, I think the most common use-case for it would include exposing additional operations, which is likely to be very difficult.
