### ISSUE TITLE
Make evmap generic over underlying map

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/rust-evmap#15]
It would be _really_ great if `evmap` could be generic over the underlying map implementation. This may not be [possible](https://internals.rust-lang.org/t/collection-traits-take-2/1272), but it would let us support use-cases like [this one](https://github.com/Amanieu/hashbrown/issues/43) by supporting [`IndexMap`](https://docs.rs/indexmap/) as one of the map types. Given that we only support a subset of the operations on maps anyway, maybe it's doable?

**Comment by jonhoo** [comment]
Haha, @novacrazy, looks like we both had the same thought at the same time. Closing in favor of #14.

**Comment by novacrazy** [comment]
Jinx 😄
