### ISSUE TITLE
u256 (sha256)

### ISSUE THREAD

**Issue by pakipaki2000** [jonhoo/rust-evmap#21]
Hi;
Me again :)

I'd like to store u256 or u8;32 (sha256 hashes) as key/value.

How can i insert it here:
pub struct AppState {
    read: evmap::ReadHandle<u64, u64>,
    write: Arc<Mutex<evmap::WriteHandle<u64, u64>>>,
}

I tried to put it it says:
the trait `evmap::shallow_copy::ShallowCopy` is not implemented for `[u8; 32]`

Thanks :)

**Comment by novacrazy** [comment]
Honestly, I would just wrap the byte array and implement `ShallowCopy` myself:

```rust
use std::fmt;
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MyHash(pub [u8; 32]);

impl fmt::Display for MyHash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:X?}", self.0)
    }
}

impl evmap::ShallowCopy for MyHash {
    #[inline]
    unsafe fn shallow_copy(&mut self) -> Self {
        MyHash(self.0)
    }
}

pub struct AppState {
    read: evmap::ReadHandle<MyHash, MyHash>,
    write: Arc<Mutex<evmap::WriteHandle<MyHash, MyHash>>>,
}
```

because all arrays with `Copy` elements are `Copy` themselves, it's super simple.

**Comment by pakipaki2000** [comment]
Thank you so much again :)

PS: I literally laughed when you said: "it's super simple" :D

**Comment by novacrazy** [comment]
I did just simplify it a bit more. `*self` rather than `MyHash(self.0)`. So yeah, overall not bad. Heh.

**Comment by pakipaki2000** [comment]
One last thing about your Struct, when I take it from the evmap, how do I convert it back to u8;32 and not MyHash?

        let context = ctx.state().read.get_and(&go, |results| results[0]);
        match context {
            Some(pubkey) => {
                //log_request();
                context: &[u8] = pubkey; // ? HOW

                println!("good");
            }

            None => println!("Cannot get"),
        }

**Comment by novacrazy** [comment]
You should be able to do something like:

```rust
let hash_slice: &[u8] = &pubkey.0;
```

or you could implement `Deref`/`AsRef` for `MyHash` like:

```rust
impl AsRef<[u8]> for MyHash {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

// ...
let hash: &[u8] = pubkey.as_ref();
// ...
```

**Comment by pakipaki2000** [comment]
expected &[u8], found enum `std::option::Option

                      let con: &[u8] = pubkey.as_ref();

**Comment by pakipaki2000** [comment]
Thanks! It's working
