### ISSUE TITLE
Reader not seeing writes even after refresh?

### ISSUE THREAD

**Issue by Sushisource** [jonhoo/rust-evmap#33]
I was implementing my own LRU cache on top of evmap and was having problems, decided to re-implement the test with *just* evmap and I think I may have found a bug where this test usually fails with the `len()` being `0`. Occasionally it passes.

```rust
    #[test]
    fn ev_multi_threaded() {
        let (read_handle, mut write_handle) = evmap::new();
        let reader_a = read_handle.clone();
        let reader_b = read_handle.clone();
        let reader_c = read_handle.clone();
        let barrier = Arc::new(Barrier::new(4));
        let ba = barrier.clone();
        let bb = barrier.clone();
        let bc = barrier.clone();
        // The write-side thread (the one that does inserts)
        std::thread::spawn(move || {
            for i in 1..=10 {
                write_handle.insert(i, i.to_string());
                write_handle.refresh();
            }
            dbg!("A");
            ba.wait();
        });
        // Two "read" sides
        std::thread::spawn(move || {
            while let None = reader_a.get_and(&6, |v| v[0].clone()) {}
            while let None = reader_a.get_and(&8, |v| v[0].clone()) {}
            dbg!("B");
            bb.wait();
        });
        std::thread::spawn(move || {
            while let None = reader_b.get_and(&7, |v| v[0].clone()) {}
            while let None = reader_b.get_and(&9, |v| v[0].clone()) {}
            dbg!("C");
            bc.wait();
        });
        barrier.wait();
        dbg!("Done");
        assert_eq!(reader_c.len(), 10);
    }
```

Am I misusing something here? I might be doing dumb things with Barrier. From what I can tell this should pass consistently. You can even put a long sleep in before the call to len() and it'll still fail.

Thanks for your work on this library! Hopefully this helps and isn't a fluke.

**Comment by Sushisource** [comment]
Nevermind. I am doing dumb things. This is failing because the only write handle gets dropped - is that right?

**Comment by jonhoo** [comment]
Ah, yes, when the write handle goes away, the reads will all treat the map as empty. This is a little unfortunate, but had to happen in 25 due to #24. Perhaps you can think of a good update to the documentation to mention this?

**Comment by jonhoo** [comment]
I'm going to close this. @Sushisource if you can think of a good update to the documentation to help future users with this, I'd love a PR!
