### ISSUE TITLE
Async refresh

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [jonhoo/rust-evmap#37]
Any plans on making async version of refresh?

**Comment by jonhoo** [comment]
_Probably_ not. Trying to weave this into the waker mechanic is going to take some doing, and is actually far from straightforward. Would love to take a look at a PR if someone is feeling up to the challenge though!

**Comment by jonhoo** [comment]
I'll close this for now, but would still be happy to take a look if someone has a PR in mind!
