### ISSUE TITLE
possible to include examples of using evmap across threads? 

### ISSUE THREAD

**Issue by jonathanstrong** [jonhoo/rust-evmap#4]
I'm working through which data structures to use in a project and came across this. It looks promising however I'm fairly confused about using it across threads. Eventually I came across the benchmark code and saw that for multiple writers you are wrapping the writer handle in Arc<Mutex<_>>. If you need arc mutex for writing is there still a gain in performance? Is that because the reader handle can still be used? These things are not obvious to someone who is trying to understand a concurrent hashmap for the first time! The examples in the docs are good for how to insert/modify/access but don't address how to use it in its primary use case. (Not said in criticism, just to provide a helpful perspective from someone who is looking at it for the first time. Thanks for making the library available!)

**Comment by jonhoo** [comment]
Hi there!

`evmap` is primarily intended for the single-writer, multi-reader use-case; this is why you can have multiple read handles (i.e., `ReadHandle: Clone`), but only one write handle. `Arc<Mutex<WriteHandle>>` allows you to have multiple threads do writes, but they will need to do them sequentially (as the `Mutex` implies). You are completely right that this will not scale well when you have many writers, but that's the trade-off `evmap` makes. Instead, `evmap` is heavily optimized for when you have a *lot* of readers that all want to access the map concurrently (including while the writer is operating). This is why you *don't* need to wrap `ReadHandle` in an `Arc<Mutex<_>>`.

As for how to improve the documentation and/or examples, I'd be happy to hear what changes you would suggest making. Would a multi-threaded example be enough?

**Comment by jonathanstrong** [comment]
This is a great explanation, thank you. I think if you put essentially that text (with some edits to supply the context) in the docs it would go a long way. The other thing would just be an example of sending a `clone()`ed reader to another thread while needing the mutex for the writer, perhaps. 

I've been thinking about this and this may make sense for my situation even if I need a mutex for the writer. Even though I have several threads that need to be able to write (< 20), they aren't writing very often (less than once a second) and are unlikely to be writing at the same time. If I get faster reads and about the same write time then it could be a win.
