### ISSUE TITLE
concurrent-map-bench does not compile

### ISSUE THREAD

**Issue by uce** [jonhoo/rust-evmap#49]
Building `concurrent-map-bench` in `benchmark` results in:

```
$ cargo build --release
...
error[E0599]: no method named `get_and` found for reference `&evmap::ReadHandle<u64, u64>` in the current scope
   --> src/main.rs:228:15
    |
228 |             r.get_and(&key, |v| v[0]).unwrap_or(0)
    |               ^^^^^^^ method not found in `&evmap::ReadHandle<u64, u64>`
```

I think this is caused by the API change in a55390c.

---

When I build the crate with cargo, I see the `evmap` dependency updated in `Cargo.lock` (9.0 vs. the committed 7.0). I think this is expected for a local `path` dependency, but please let me know if I'm doing something unexpected (I'm new to Rust).

If you can confirm that this is an issue, I'd be happy to create a PR with a fix.

**Comment by jonhoo** [comment]
Ah, good catch! Should be fixed in #50
