### ISSUE TITLE
Memory bloat when using with async runtime

### ISSUE THREAD

**Issue by aXenom** [jonhoo/rust-evmap#53]
Hi, this is my very first issue on Github (yeah, really), so I'm sorry in advance if I'll do something wrong here.

Consider this simple example:
```rust
use std::net::SocketAddr;
use hyper::{Request, Response, Body, Error, Server};
use hyper::service::{service_fn, make_service_fn};

async fn handle(
    _req: Request<Body>,
    _routes: evmap::ReadHandle<&str, &str>
) -> Result<Response<Body>, Error> {
    Ok(Response::new(Body::from("Hello world")))
}

#[tokio::main]
async fn main() {
    let (map_reader, mut map_writer) = evmap::new();
    map_writer.insert("test", "value");
    map_writer.refresh();

    let svc = make_service_fn(move |_| {
        let data = map_reader.clone();
        async {
            Ok::<_, Error>(service_fn(move |req| {
                handle(req, data.clone())
            }))
        }
    });

    let addr: SocketAddr = "127.0.0.1:3000".parse().unwrap();
    let server = Server::bind(&addr).serve(svc);

    if let Err(err) = server.await {
        println!("server error: {}", err);
    }
}
```

This code does compile.
Here's the list of dependencies for this example, fairly straightforward:
```toml
[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
evmap = "10.0"
```
However, the application consumes ever-growing amount of memory, and it becomes specifically obvious under load testing. It doesn't matter whether `_routes` is actually used in the handler. After the handler was executed multiple times, if we print the ReadHandle afterwards, we would see something like this:

```
ReadHandle {
    epochs: Mutex {
        data: [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
    },
    epoch: 0,
    my_epoch: 0,
}
```
The `data` inside the Mutex grows indefinitely, causing a memory bloat.

Thank you!

**Comment by jonhoo** [comment]
Ah, this is interesting. It's not _technically_ a memory leak, but you have indeed identified a problem. I have put up a PR to fix it with more details here: https://github.com/jonhoo/rust-evmap/pull/54.

The deeper reason why you saw a problem is that you are cloning a lot of `ReadHandle` instances. evmap generally works better if a `ReadHandle` is used for a while, rather than constantly being replaced (which is what all your calls to `clone` effectively do). I think you can get rid of at least one of those clones, but could be wrong.

**Comment by aXenom** [comment]
Thanks a lot!

I was suspecting the root cause and speculated about it in the first version of the issue, but wasn't too certain about it and deleted my speculation afterwards 😄

> I think you can get rid of at least one of those clones, but could be wrong.
There are examples with different requirements: [here](https://github.com/hyperium/hyper/blob/master/examples/state.rs#L30) the reference is cloned once (probably because the data structure is simple), and [here](https://github.com/hyperium/hyper/blob/master/examples/web_api.rs#L106) it needs to be cloned twice and doesn't compile otherwise; #11 is an example of the issue.

I suppose that this library is intended to be used in a more controlled manner, when the amount of readers is more or less stable, or at least predetermined. It's just this weird domain of web applications continues to introduce its weird use cases.
