### ISSUE TITLE
#[derive(ShallowCopy)] has prohibitive "T: ShallowCopy" bound

### ISSUE THREAD

**Issue by cyphar** [jonhoo/rust-evmap#63]
Currently if you wish to use `evmap_derive::ShallowCopy` for some thing like:

```
pub struct ShallowArc<T>(Arc<T>); // or more complicated structures
```

The generated trait implementation has a `T: ShallowCopy` bound, which is unnecessary -- the `ShallowCopy` impl for `Arc<T>` doesn't have such a bound and if the code was just generated without the bound it should compile without issues -- here's the open-coded version I used (though I will admit this may be entirely wrong -- though the fact that `Arc<T>` is safe leads me to think that this must also be safe):

```
impl<T> ShallowCopy for ShallowArc<T> {
    // SAFETY: This is safe because the evmap crate's ShallowCopy implementation
    // is safe for Arc.
    unsafe fn shallow_copy(&self) -> ManuallyDrop<Self> {
        ManuallyDrop::new(Self(ManuallyDrop::into_inner(self.0.shallow_copy())))
    }
}
```

The same applies for `Box`, `Rc`, and probably more examples.

For background, the reason why you'd want to have `struct ShallowArc<T>(Arc<T>)` is because `Arc<T>` implements deep equality and hashing, but for my use-case I strictly care about inner-pointer equality (`Arc::ptr_eq`). Also my `T` contains `RwLock` and other structures which cannot be compared or hashed. So I need to wrap `Arc<T>` -- and `ShallowArc` is being used only in a single-value `evmap` anyway.

**Comment by cyphar** [comment]
To be fair, this is a bit hard to get right all the time because you have to deal with cases like

```
impl<T> ShallowCopy for Foo<T>
where
  T: ShallowCopy { /* ... */ }

#[derive(ShallowCopy)]
struct Bar<T>(Foo<T>);
```

**Comment by cyphar** [comment]
> Specifically, it is only safe to derive ShallowCopy for a struct where all the fields are ShallowCopy.

We're in complete agreement on that, but that isn't really what the current bound is (the bound is related to generic parameters, not the fields). But you're quite right that `Clone` has similar semantics (I didn't know that until I just tried it out), though my point is mainly that there are cases where this leads to strange results:

```
#[derive(ShallowCopy)]
struct Foo<T>(T); // You can use Foo<Arc<T>> regardless of whether T fulfills ShallowCopy.

#[derive(ShallowCopy)]
struct Foo<T>(Arc<T>); // You can't use Foo<T> unless T fulfills ShallowCopy.
```

But I guess this is more of a limitation of `#[derive(...)]` macros and trait bounds than anything else -- especially since `Clone` has the same limitation.

**Comment by jonhoo** [comment]
Yeah, unfortunately. Although we _may_ be able to fix that by instead generating some code to assert that each field type is `ShallowCopy` specifically. Doing so is definitely tricky, if not currently impossible, but in _theory_ it should be doable. @MayaWolf may be a good person to check in with.
