### ISSUE TITLE
Thread Safety Error on ReadHandler

### ISSUE THREAD

**Issue by Jarves42** [jonhoo/rust-evmap#65]
I have created a TCP server which adds a random number to evmap and sends all the value for a given test key.

I am facing `std::cell::Cell<()> cannot be shared between threads safely` error if I spawn a thread for each HTTP req.

evmap is concurrent data struct so I think we are able to do crud op concurrently using multiple threads. 

Below is the exact code. 

Please point out if anything wrong I am doing or any change by which I can read/update evmap using threads.

```rust
use std::sync::Mutex;
use rand::Rng;
use std::net::{TcpListener};
use std::io::{Write};
use std::thread;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:8080").unwrap();
    println!("Listening for connections on port {}", 8080);

    let (read_handler, write_handler) = evmap::new();
    let write_lock = Mutex::new(write_handler);

    for stream in listener.incoming() {
        match stream {
            Ok(mut stream) => {
                thread::spawn(|| {
                    let mut rand_generator = rand::thread_rng();
                    let mut lock = write_lock.lock().unwrap();
                    let random_number = rand_generator.gen_range(0, 100);
                    lock.insert("1".to_string(), random_number);
                    lock.refresh();

                    let mut response = String::new();
                    if let Some(values) = read_handler.clone().get("1") {
                        for value in values.iter() {
                            if response.len() > 0 {
                                response.push_str("~");
                            }
                            response.push_str(format!("{}", *value).as_str());
                        }
                    }

                    let response = format!("HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n<html><body>{}</body></html>\r\n", response);
                    stream.write(response.as_bytes()).unwrap();
                });
            }
            Err(e) => {
                println!("Unable to connect: {}", e);
            }
        }
    }
}
```

**Comment by jonhoo** [comment]
Hi there! So, what you're running into is that evmap does not let you share a single `ReadHandle`. Instead, you need to keep one clone of the handle for each concurrent place you want to access the map from. In your case above, just add
```rust
let read_handler = read_handler.clone()
```
above the call to `thread::spawn`, and make the closure `move ||`. That _should_ do it.

**Comment by Shoowa** [comment]
After cloning the `read_handler` like @jonhoo advised, I think the _mutex_ can be wrapped with a thread-safe reference-counting pointer, i.e. Arc.
```rust
let write_lock = Arc::new(Mutex::new(write_handler));
```
And then inside the OK branch, the action of `Arc::clone` around a reference to the lock will successfully pass into the closure.

```rust
let write_lock = Arc::clone(&write_lock);
```
After inserting the aforementioned changes, I successfully ran the script.

**Comment by jonhoo** [comment]
Yes, the write handle does _not_ support concurrent operations in evmap, so you'd need to wrap it in a `Mutex` to share it :)
