### ISSUE TITLE
Relaxation of epoch invariant

### ISSUE THREAD

**Issue by ratmice** [jonhoo/rust-evmap#76]
During the last stream the epoch invariant came up, specifically that it is currently `increasing`, and `greater than`,
Someone (not sure who), mentioned that it could be relaxed, to `wrapping`, and `not equal`.

This is an argument for why the above relaxation is correct:
* `std::u{N}::MAX == 2 ^ N - 1` is odd,
* `std::u{N}::MAX + 1 == 0` is even,

Therefore when epoch wrapping occurs a reader is exiting a `leftright`, and the meaning ascribed to even and odd shouldn't flip.

I'm not sure of the cycle for variously sized types of atomic instructions, but perhaps this would allow a faster atomic type to be chosen (whatever is fast, but still lessens the probability of writer reading the same value twice as a reader wraps around).

Though it probably would take a real short enter/read/exit to actually matter, its a potential micro-optimization which removes of a theoretical panic, so I believe its worthwhile.

**Comment by jonhoo** [comment]
Note to self: for us to do this, I'd also have to change the logic to _actually_ do even/odd rather than the high bit trick it does at the moment.

**Comment by jonhoo** [comment]
Fun fact: while looking at the code to implement this, I realized that the check is actually already `!=` :p
