### ISSUE TITLE
A potential alternative to epochs, if it works

### ISSUE THREAD

**Issue by dylanfoxx** [jonhoo/rust-evmap#80]
When I was thinking about how epochs work and some ways to “improve” the implementing I came up with a new idea. I have no idea if it will work as well as epochs or if it is correct. I was hoping for some feedback on the idea, any error cases I overlooked or other improvements. After the holiday week when I have free time I hope to try implementing it (If there are no huge flaws).

When I tried explaining the epoch system to someone they replied with “why not use an ARC".  There are a few reasons why ARCs do not work but it got me thinking. Is there a lock free way where each reader did not need to keep a personal state and where they can tell the writer when they are done with the "map"?

Seeing as I have not made it and I'm asking you to double check me I'm not sure. But I hope the idea is close or will spark more ideas. I will be trying to consolidate the idea but seeing as this is the first time I'm writing it all out in one place it may get a bit messy.

This is the basic idea of what the struct(have not named it yet) would look like.

struct {
  active_ptr: atomic_ptr, // For active "Map"
  active_bucket: atomic_u8, // What bucket is "active"
  (atomic_usize, atomic_usize) "Buckets"  // “active”, “next”
}

Basically the idea revolves around making a “clean” bucket and then waiting for the “dirt” bucket(s) to empty. We can guarantee that the clean bucket readers have only the active pointer but we are unsure of the dirty bucket(s). The dirty bucket(s) could be the old pointer(old pointer old bucket) or the new pointer (old bucket new pointer).

How it works:

Reader
1. Read/save the active_bucket as local saved_active_bucket
2. Show readers intention to read "Buckets"[saved_active_bucket]++ (check to see if we are at max)
2 (Error case) if the active_bucket is changed then we could be in either the wrong bucket or correct bucket if multiple changes occurred. Either way the pointer is correct and the writer is waiting on us to finish if we are in the wrong bucket.
3. Read the pointer
4. Do what you need to …
5. Show you are done with the associated bucket "Buckets"[saved_active_bucket]-- (check to see if we are at 0. If so “call” the writer)

Writer
1. Swap active_ptr
2. Make sure the “next” bucket has no readers (Make sure no-one snuck in before we swapped or is left over from previous swap)
2 (Error case).  Wait for a "call" from readers emptying maps. We can proceed when the “next” bucket hits 0. 
4. change active_bucket to “next”
5. check to see if any(not active_bucket) bucket is at 0. if so mark it. (We don’t need to check later if they are at 0 now. Extends to multiple buckets)
6. If old bucket(s) were not at 0 when we checked Wait for 0 “call” on non active bucket(s) (if buckets hit 0 we can swap. Even if they count up after)

Error cases
- I cannot think of any more than what I have already listed.

Clarifying
- When I say “Call” there needs to be a thread safe way for each bucket(reader) to tell a writer it is finished. This will most likely need to be a convar or single MPSC.
- When I say “Buckets” it can be a tuple, array or anything that we can index. I am sticking to 2 buckets for now but I believe we can be expanded to more.

More ideas
- I think there is a way to add another writer by adding more buckets but lets work on the one writer case for now.
- For a reader if we know we want to do another read there is “potential” optimizations we can make here by comparing our saved_active_bucket(or the pointer) to the active_bucket(or pointer). If it is the same no writer has attempted to swap … that we know of. I have no idea if this will help but its an idea.
- The same idea as above can be used to check if our reading is “outdated”(A new map has been published during our read). It will never be perfect but its one thing we can do to get closer.
- To possibly reduce contention we can make more buckets or spread out each atomic so it is not on the same cache line … maybe?
- Can we make the pointer and active_bucket one large atomic? Would that benefit us at all? I don't think so because we would need to check that we did not overwrite the pointer when we increment.

Down sides
- Readers have to do more work. At least least one more read and whatever work is needed to “call” the writer.
- More contention on the shared counters?
- Writer may need to wait longer as it needs to clear 2+ buckets
- We will have to wait for the next bucket to empty. This could take longer then just checking ever reader. (Some of this could still happen on epochs if we move to a u8 but they would need to perform a lot of reads) – I feel like this could be mitigated if we add more buckets.

Up sides?
- Readers can have 0 size. They can just walk up and read no need to register as a reader.
- Writer does not need to know about readers directly
- Writer can “sleep” and wait to be told about changes
- It is fixed size. No need for new allocations. Disregarding the need to expand the “map” 

Thinks I don’t know
- I have no idea if the trade off is worth anything for this project. I need to run benchmarks after it has been proven and implemented. 
- I am not great with atomics so I may have overlooked something here.

Final
There may be a few issues with it as I have already made minor changes to make it work since I originally came up with it. If this already exists under a different name let me know. Ask questions and try to pick it apart. Also if it was not already “invented” suggest names.

**Comment by jonhoo** [comment]
So, I think the place you run into issues with this scheme is that all the readers are contending on the bucket counters. That is a single shared cache line that all readers must constantly modify, which quickly stops scaling, especially on something like a NUMA architecture. That said, since it's only `fetch_add`, it _might_ still scale pretty well. My suggestion would be to try implementing it and see how it works out! I'm going to close this issue here though, since it's not really about evmap/left-right :)
